export default [
	{ text: "CSS引入方式", link: "/guide/css/css引入方式" },
	{
		text: "选择器",
		link: "/guide/css/选择器",
	},
	{
		text: "三大特性",
		link: "/guide/css/三大特性",
	},
	{
		text: "字体属性",
		link: "/guide/css/font",
	},
	{
		text: "文本属性",
		link: "/guide/css/text",
	},
	{ text: "颜色", link: "/guide/css/颜色" },
	{ text: "列表属性", link: "/guide/css/列表属性" },
	{ text: "边框属性", link: "/guide/css/边框属性" },
	{ text: "边距属性", link: "/guide/css/边距属性" },
	{ text: "背景属性", link: "/guide/css/背景属性" },
	{ text: "元素显示模式", link: "/guide/css/元素显示模式" },
	{ text: "浮动", link: "/guide/css/浮动" },
	{ text: "定位", link: "/guide/css/定位" },
	{ text: "过渡", link: "/guide/css/过渡" },
	{ text: "变换", link: "/guide/css/变换" },
	{ text: "动画", link: "/guide/css/动画" },
	{ text: "css单位", link: "/guide/css/css单位" },
	{ text: "CSS常用架构", link: "/guide/css/css常用架构" },
	{
		text: "CSS常见布局",
    link: "/guide/css/css常见布局",
	},
	{ text: "seo", link: "/guide/css/seo" },
	{ text: "精灵图", link: "/guide/css/精灵图" },
	{ text: "字体图标", link: "/guide/css/字体图标" },
	{ text: "css三角", link: "/guide/css/css三角" },
	{ text: "用户界面样式", link: "/guide/css/用户界面样式" },
	{ text: "最佳实践", link: "/guide/css/最佳实践" },
	{ text: "扩展", link: "/guide/css/扩展" },
]
